### ISSUE TITLE
Kaitai Struct modeling

### ISSUE THREAD

**Issue by krisutofu** [PistonMiner/ttyd-tools#9]
I took some time in my current holidays to start reverse-engineering the anim group file format but until now I didn't know what progress others made in reverse-engineering and editing the game.

I used Kaitai Struct as a language independent file parsing DSL. Would it be okay to contribute some Kaitai struct definitions? They can be used to automatically generate code in many languages, including Nim.

Btw, I have personal and technical problems with Discord. Right after registration and joining your modding group my account was disabled despite the high registration effort that is needed. Are there other ways of communication for the group?

**Comment by PistonMiner** [comment]
> I used Kaitai Struct as a language independent file parsing DSL. Would it be okay to contribute some Kaitai struct definitions? They can be used to automatically generate code in many languages, including Nim.

This sounds like the sort of thing that would fit better in some kind of repo of your own. Over the years everyone has sort of accumulated their own tooling, I just keep the stuff that I maintain in here (with a couple of exceptions).

> Btw, I have personal and technical problems with Discord. Right after registration and joining your modding group my account was disabled despite the high registration effort that is needed. Are there other ways of communication for the group?

This sounds like an issue on the side of Discord-- nothing I can really do about that unfortunately. I don't think any of the big forums for TTYD modding stuff are bridged to something outside of Discord right now.
